// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2024-Present The UDS Authors
// Generated by hack/main.go do not edit this file directly, edit the types and regenerate with go generate in the hack directory

export interface Gen {
    Application?: Application;
    [property: string]: any;
}

export interface Application {
    kind?:     string;
    metadata?: Metadata;
    spec?:     Spec;
    [property: string]: any;
}

export interface Metadata {
    name?: string;
    [property: string]: any;
}

export interface Spec {
    architecture?:       Architecture[];
    categories?:         Category[];
    contractingDetails?: ContractingDetails;
    description?:        string;
    icons?:              IconElement[];
    infrastructure?:     SupportedInfrastructure[];
    keywords?:           string[];
    links?:              LinkElement[];
    repository?:         string;
    security?:           Security;
    tagline?:            string;
    title?:              string;
    vendor?:             Vendor;
    versions?:           string[];
    [property: string]: any;
}

export enum Architecture {
    Amd64 = "amd64",
    Arm64 = "arm64",
}

export enum Category {
    AIMl = "AI/ML",
    Arcade = "Arcade",
    Collaboration = "Collaboration",
    CommandAndControl = "Command and Control",
    Databases = "Databases",
    DigitalEngineering = "Digital Engineering",
    ITManagement = "IT Management",
    Kubernetes = "Kubernetes (K8s)",
    Networking = "Networking",
    Productivity = "Productivity",
    Security = "Security",
    SoftwareDev = "Software Dev",
    SpaceOperations = "Space Operations",
    Web = "Web",
}

export interface ContractingDetails {
    number?:              string;
    pricingModel?:        PricingModel[];
    smallBusinessStatus?: string;
    vehicle?:             string[];
    [property: string]: any;
}

export enum PricingModel {
    BringYourOwnLicense = "Bring Your Own License",
    Free = "Free",
}

export interface IconElement {
    size?: string;
    src?:  string;
    type?: string;
    [property: string]: any;
}

export enum SupportedInfrastructure {
    AWSGov = "AWS GovCloud (US)",
    AzureGov = "Azure Government Cloud",
    OnPrem = "On-prem",
    Edge = "Edge",
}

export enum Security {
    FIPSImage = "FIPS Image",
    NIST80052ControlsMapped = "NIST 800-52 Controls Mapped",
}

export interface LinkElement {
    description?: string;
    url?:         string;
    [property: string]: any;
}

export enum ImpactLevel {
    The2 = "2",
    The4 = "4",
    The5 = "5",
    The6 = "6",
}

export interface Vendor {
    icons?: IconElement[];
    name?:  string;
    url?:   string;
    [property: string]: any;
}
