// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2024-Present The UDS Authors
// Generated by hack/main.go do not edit this file directly, edit the types and regenerate with go generate in the hack directory

export interface Gen {
    Application?: Application;
    [property: string]: any;
}

export interface Application {
    kind?:     string;
    metadata?: Metadata;
    spec?:     Spec;
    [property: string]: any;
}

export interface Metadata {
    name?: string;
    [property: string]: any;
}

export interface Spec {
    architecture?:       Architecture[];
    categories?:         Category[];
    contractingDetails?: ContractingDetails;
    description?:        string;
    icons?:              IconElement[];
    infrastructure?:     Infrastructure[];
    keywords?:           string[];
    links?:              LinkElement[];
    repository?:         string;
    security?:           Security;
    tagline?:            string;
    title?:              string;
    vendor?:             Vendor;
    versions?:           string[];
    [property: string]: any;
}

export enum Architecture {
    Amd64 = "amd64",
    Arm64 = "arm64",
}

export enum Category {
    AIMl = "AI/ML",
    Arcade = "Arcade",
    Business = "Business",
    Databases = "Databases",
    DevelopmentTools = "Development Tools",
    Kubernetes = "Kubernetes",
    Networking = "Networking",
    Productivity = "Productivity",
    Security = "Security",
    Web = "Web",
}

export interface ContractingDetails {
    number?:              string;
    pricingModel?:        PricingModel[];
    smallBusinessStatus?: string;
    vehicle?:             string[];
    [property: string]: any;
}

export enum PricingModel {
    BringYourOwnLicense = "Bring Your Own License",
    Free = "Free",
}

export interface IconElement {
    size?: string;
    src?:  string;
    type?: string;
    [property: string]: any;
}

export enum Infrastructure {
    AWSGov = "AWS Gov",
    AirGapped = "AirGapped",
    AzureGov = "Azure Gov",
    OnPrem = "On-Prem",
}

export interface LinkElement {
    description?: string;
    url?:         string;
    [property: string]: any;
}

export interface Security {
    cveReport?:   boolean;
    fips?:        boolean;
    impactLevel?: ImpactLevel[];
    nist80053?:   boolean;
    sbom?:        boolean;
    [property: string]: any;
}

export enum ImpactLevel {
    The2 = "2",
    The4 = "4",
    The5 = "5",
    The6 = "6",
}

export interface Vendor {
    icons?: IconElement[];
    name?:  string;
    url?:   string;
    [property: string]: any;
}
