// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2024-Present The UDS Authors
// Generated by hack/main.go do not edit this file directly, edit the types and regenerate with go generate in the hack directory

export interface Gen {
    Application?: Application;
}

export interface Application {
    description?:  string;
    icon_path?:    string;
    keywords?:     string[];
    links?:        Empty[];
    name?:         string;
    repositories?: string[];
    tagline?:      string;
    title?:        string;
}

export interface Empty {
    description?: string;
    url?:         string;
}
