apiVersion: apps/v1
kind: Deployment
metadata:
  name: uds-appstore
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: uds-appstore
  template:
    metadata:
      labels:
        app: uds-appstore
    spec:
      serviceAccountName: uds-appstore-sa
      containers:
        - name: uds-appstore
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "750m"
