apiVersion: v1
kind: Service
metadata:
  name: uds-appstore
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: uds-appstore
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
