apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: uds-appstore
  namespace: {{ .Release.Namespace }}
spec:
  network:
    expose:
      - service: uds-appstore
        selector:
          app: uds-appstore
        host: apps
        gateway: tenant
        port: 8080
        targetPort: 8080
    allow:
      - direction: Egress
        selector:
          app: uds-appstore
        remoteGenerated: KubeAPI
