# yaml-language-server: $schema=https://raw.githubusercontent.com/defenseunicorns/maru-runner/main/tasks.schema.json
includes:
  - common: https://raw.githubusercontent.com/defenseunicorns/uds-common/v0.9.0/tasks/lint.yaml
  - setup: ./setup.yaml

tasks:
  - name: all
    description: "Run all linters"
    actions:
      - task: yaml
      - task: golangci
      - task: ui

  - name: golangci
    description: "Run golang linters"
    actions:
      - cmd: which golangci-lint || echo "install golangci-lint -- https://golangci-lint.run/welcome/install/#local-installation" exit 1
      - cmd: golangci-lint run --timeout 5m0s

  - name: yaml
    description: "Run yaml linters"
    actions:
      - task: common:deps
      - task: common:yaml

  - name: ui
    description: "Run ui linters"
    actions:
      - cmd: npx pnpm i && npm run lint
        dir: ui

  - name: format-ui
    description: "Format ui code"
    actions:
      - cmd: npx pnpm i && npm run format -- --write
        dir: ui

  - name: pre-commit
    description: "Run pre-commit hooks"
    actions:
      - cmd: pre-commit run --all-files
