# yaml-language-server: $schema=https://raw.githubusercontent.com/defenseunicorns/maru-runner/main/tasks.schema.json
includes:
  - common: https://raw.githubusercontent.com/defenseunicorns/uds-common/v0.9.0/tasks/setup.yaml

tasks:
  - name: install-tools
    description: "Install all tools"
    actions:
      - task: golangci
      - task: pre-commit
      - task: oras

  - name: golangci
    description: "Install golangci-lint to GOPATH using install.sh"
    actions:
      - cmd: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.59.1

  - name: yamllint
    description: "Install yamllint using venv"
    actions:
      - cmd: python3 -m venv .venv
      - cmd: source .venv/bin/activate
      - cmd: pip install yamllint

  - name: pre-commit
    description: "Install pre-commit using homebrew"
    actions:
      - cmd: brew install pre-commit

  - name: deps
    description: "lock and tidy dependencies"
    actions:
      - cmd: npx pnpm i
        dir: ui
      - cmd: npx playwright install
        dir: ui
      - cmd: go mod tidy

  - name: oras
    description: "Install oras cli"
    actions:
      - cmd: brew install oras
